controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    f1tenth_controller:
      type: ackermann_steering_controller/AckermannSteeringController

f1tenth_controller:
  ros__parameters:
    rear_wheels_names:
      - left_rear_wheel_joint
      - right_rear_wheel_joint
      

    front_wheels_names:
      - left_steering_hinge_joint
      - right_steering_hinge_joint
    
    front_steering_names:
      - left_steering_hinge_joint
      - right_steering_hinge_joint


    wheelbase: 0.33
    
    # Ganti 'track' jadi ini:
    front_wheel_track: 0.2
    rear_wheel_track: 0.2
    
    # Ganti 'wheel_radius' jadi ini:
    front_wheels_radius: 0.05
    rear_wheels_radius: 0.05

    # --- 3. Lain-lain ---
    open_loop: false 
    
    # Limits
    max_steering_angle: 0.523 
    max_speed: 5.0 

    # Odometry
    base_frame_id: chassis
    odom_frame_id: odom
    enable_odom_tf: true 
    
    publish_rate: 50.0
    velocity_rolling_window_size: 10
